sudo: required 

language: go

go: 
  - 1.x

services:
  - docker
  
install:
  - go get -t -v ./...

script: 
  - make creds
  - make deps
  - make test

before_script:
  - go get -v github.com/golang/lint/golint
 
  

  
  
