sudo: required
language: go
services:
- docker
before_install:
- docker pull rackhd/golang:1.8.3
- docker run -it rackhd/golang:1.8.3
- echo ${PWD}
- export GIT_SSL_NO_VERIFY=1
mkdir -p /go/src/github.com/dellemc-symphony/
cd /go/src/github.com/dellemc-symphony/
git clone https://github.com/dellemc-symphony/workflow-cli.git
script:
- cd /go/src/github.com/dellemc-symphony/workflow-cli/
- make creds
- make deps
